dist: trusty

language: 'node_js'
node_js:
  - '8'

os: 
  -macosx

script: gulp travis

services:
  - mongodb
  - postgresql

cache:
  directories:
    - 'node_modules'

install:
  - npm install 

before_script:
  - sleep 15
  - npm run start:build
  - npm run buildEnv
  - npm run start
  
  
