language: 'node_js'
node_js:
  - '8'

script: gulp travis

services:
  - mongodb
  - postgresql

cache:
  directories:
    - 'node_modules'

before_script:
  - sleep 15
  - npm run test
  - npm run buildEnv
  - npm run start
  
  
